apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tzdj37pwd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tzdj37pwd-python 
  name: tzdj37pwd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tzdj37pwd-python 
